<?php

namespace Kirby\App;

use Kirby\Toolkit\Response;

// direct access protection
if(!defined('KIRBY')) die('Direct access is not allowed');

/**
 * Controller
 * 
 * The main controller class, which will be used as 
 * base for all custom controllers
 * 
 * @package   Kirby App
 * @author    Bastian Allgeier <bastian@getkirby.com>
 * @link      http://getkirby.com
 * @copyright Bastian Allgeier
 * @license   http://www.opensource.org/licenses/mit-license.php MIT License
 */
class Controller {

  // the controller name
  public $name;

  // the parent module
  public $module;

  // the default layout
  public $layout;

  // the current action
  public $action;

  // the response format
  public $format = 'html';

  // additional arguments for the action
  public $arguments;

  /**
   * Constructor
   */
  public function __construct() {
    $this->name = str_replace('controller', '', strtolower(get_called_class()));
  }

  /**
   * Returns the controller name
   * 
   * @return string
   */
  public function name() {
    return $this->name;
  }

  /**
   * Returns the parent module object
   * 
   * @return object
   */
  public function module() {
    return $this->module;
  }

  /**
   * Returns the default layout object if available
   * 
   * @return object
   */
  public function layout() {
    return $this->layout;
  }

  /**
   * Returns the name of the current action
   * 
   * @return string
   */
  public function action() {
    return $this->action;
  }

  /**
   * Returns the response format
   * 
   * @return string
   */
  public function format() {
    return $this->format;
  }

  /**
   * Runs the current action and returns the response object
   * 
   * @return object
   */
  public function run() {

    if(method_exists($this, $this->action)) {
      $output = call_user_func_array(array($this, $this->action), (array)$this->arguments);
    } else {
      raise('invalid controller action: ' . $this->action);
    }

    // if the controller has a valid layout
    // render that instead of the output generated by the action
    if(!$output and $layout = $this->layout) {
      $output = $layout->render($this->format); 
    } 

    if(is_a($output, 'Kirby\\Toolkit\\Response')) {
      return $output;
    } else {
      return new Response($output, $this->format);
    }

  }

  /**
   * Echos the rendered response
   * 
   * @return string
   */
  public function __toString() {
    return (string)$this->run();
  }

}